config/routes.rb
Rails.application.routes.draw do
  resources :tikets
  resources :users
  resources :routes
  resources :railway_stations
  resources :trains
  resources :wagons

  get 'welcome/index'
  root 'welcome#index'
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true
  belongs_to :railway_station, optional: true
  belongs_to :route, optional: true
  has_many :tikets
  has_many :wagons
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all.order('created_at DESC')
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train, notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to @train, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_url, notice: 'Train was successfully destroyed.'
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :railway_station_id, :route_id)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_with(model: train, local: true) do |form| %>

  <%= render 'common/errors', resource: train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :railway_station %>
    <%= form.collection_select :railway_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :route %>
    <%= form.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= train.railway_station.title if train.railway_station %></td>
  <td><%= train.route.name if train.route %></td>
  <td><%= train.tikets.size if train.tikets %></td>
  <td><%= train.wagons.size if train.wagons %></td>
  <td><%= link_to 'Show', train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/_wagon.html.erb
<% wagons.each do |wagon| %>
  <tr>
    <td><%= wagon.wagon_type.name %></td>
    <td><%= wagon.seats_top %></td>
    <td><%= wagon.seats_bottom %></td>
  </tr>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Current Station</th>
      <th>Current Route</th>
      <th>Tikets</th>
      <th>Wagons</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<% if @train.railway_station %>
  <p>
    <strong>Current Station:</strong>
    <%= @train.railway_station.title %>
  </p>
<% end %>

<% if @train.route %>
  <p>
    <strong>Current Route:</strong>
    <%= @train.route.name %>
  </p>
<% end %>

<% if @train.wagons %>
  <p><strong>Wagons:</strong></p>
  <table>
    <thead>
      <tr>
        <th>Type</th>
        <th>Top Seats</th>
        <th>Bottom Seats</th>
      </tr>
    </thead>
    <tbody>
      <%= render 'wagon', wagons: @train.wagons %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>