config/routes.rb
Rails.application.routes.draw do
  resources :tikets
  resources :users
  resources :routes
  resources :railway_stations
  resources :trains
  resources :wagons

  get 'welcome/index'
  root 'welcome#index'
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  validates :title, presence: true

  has_many :trains
  has_and_belongs_to_many :routes
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to @railway_station, notice: 'Railway station was successfully created.'
    else
      render :new
    end
  end

  def update
    if @railway_station.update(railway_station_params)
      redirect_to @railway_station, notice: 'Railway station was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @railway_station.destroy
    redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.'
  end

  private

  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  def railway_station_params
    params.require(:railway_station).permit(:title)
  end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/railway_stations/_form.html.erb
<%= form_with(model: railway_station, local: true) do |form| %>

  <%= render 'common/errors', resource: railway_station %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to 'Show', railway_station %></td>
  <td><%= link_to 'Edit', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Destroy', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'Main Page', root_path %>
<%= link_to 'New Railway Station', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>