config/routes.rb
Rails.application.routes.draw do
  resources :tikets
  resources :users
  resources :routes
  resources :railway_stations
  resources :trains
  resources :wagons

  get 'welcome/index'
  root 'welcome#index'
end

app/models/tiket.rb
class Tiket < ApplicationRecord
  belongs_to :train
  belongs_to :user
end

app/controllers/tikets_controller.rb
class TiketsController < ApplicationController
  before_action :set_tiket, only: [:show, :edit, :update, :destroy]

  # GET /tikets
  # GET /tikets.json
  def index
    @tikets = Tiket.all
  end

  # GET /tikets/1
  # GET /tikets/1.json
  def show
  end

  # GET /tikets/new
  def new
    @tiket = Tiket.new
  end

  # GET /tikets/1/edit
  def edit
  end

  # POST /tikets
  # POST /tikets.json
  def create
    @tiket = Tiket.new(tiket_params)

    respond_to do |format|
      if @tiket.save
        format.html { redirect_to @tiket, notice: 'Tiket was successfully created.' }
        format.json { render :show, status: :created, location: @tiket }
      else
        format.html { render :new }
        format.json { render json: @tiket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tikets/1
  # PATCH/PUT /tikets/1.json
  def update
    respond_to do |format|
      if @tiket.update(tiket_params)
        format.html { redirect_to @tiket, notice: 'Tiket was successfully updated.' }
        format.json { render :show, status: :ok, location: @tiket }
      else
        format.html { render :edit }
        format.json { render json: @tiket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tikets/1
  # DELETE /tikets/1.json
  def destroy
    @tiket.destroy
    respond_to do |format|
      format.html { redirect_to tikets_url, notice: 'Tiket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tiket
      @tiket = Tiket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tiket_params
      params.require(:tiket).permit(:train_id, :user_id)
    end
end

app/views/tikets/_form.html.erb
<%= form_with(model: tiket, local: true) do |form| %>
  <% if tiket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tiket.errors.count, "error") %> prohibited this tiket from being saved:</h2>

      <ul>
      <% tiket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :train_id %>
    <%= form.text_field :train_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tikets/edit.html.erb
<h1>Editing Tiket</h1>

<%= render 'form', tiket: @tiket %>

<%= link_to 'Show', @tiket %> |
<%= link_to 'Back', tikets_path %>

app/views/tikets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tikets</h1>

<table>
  <thead>
    <tr>
      <th>Train</th>
      <th>First Station</th>
      <th>Last Station</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tikets.each do |tiket| %>
      <tr>
        <td><%= tiket.train.number %></td>
        <td><%= tiket.train.route.railway_stations.first.title if tiket.train.route %></td>
        <td><%= tiket.train.route.railway_stations.last.title if tiket.train.route %></td>
        <td><%= tiket.user.first_name %></td>
        <td><%= link_to 'Show', tiket %></td>
        <td><%= link_to 'Edit', edit_tiket_path(tiket) %></td>
        <td><%= link_to 'Destroy', tiket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tiket', new_tiket_path %>

app/views/tikets/new.html.erb
<h1>New Tiket</h1>

<%= render 'form', tiket: @tiket %>

<%= link_to 'Back', tikets_path %>

app/views/tikets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Train:</strong>
  <%= @tiket.train %>
</p>

<p>
  <strong>User:</strong>
  <%= @tiket.user %>
</p>

<%= link_to 'Edit', edit_tiket_path(@tiket) %> |
<%= link_to 'Back', tikets_path %>